### ISSUE TITLE
Incorrect Client Address causing disconnect

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-event-hubs-python#1]
My client shows the following

```
Disconnected, reconnecting...
Disconnected will try to reconnect after 0.1 seconds
Disconnected will try to reconnect after 0.2 seconds
Disconnected will try to reconnect after 0.4 seconds
Disconnected will try to reconnect after 0.8 seconds
Disconnected will try to reconnect after 1.6 seconds
Disconnected will try to reconnect after 3.2 seconds

```

My guess is something related to the output below. Why is there an additional amqps in the url?

```
Client starts address=amqps://RootManageSharedAccessKey:REDACTED@REDACTED.servicebus.windows.net:amqps/metrics
```

**Comment by bearrito** [comment]
If you set the port directly then this issue does not appear. I'll sort out where the issue appears and submit a patch.

**Comment by bpoti001** [comment]
@bearrito  I am also having the same issue, but I am not able to understand your work around, can you please elaborate it.

**Comment by bearrito** [comment]
I believe I had to specify `443`

I will caution against using AMQP with Eventhubs and Python. It is not supported in any real way. We migrated away from it.

**Comment by chhantyal** [comment]
Use port 5671, this issue seems to go away.

However, other issue appear. As @bearrito said, this thing is really rough it seems.

**Comment by xinchen10** [comment]
it should be fixed now in master.
