### ISSUE TITLE
Infrequent segmentation fault with the EPH implementation

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-event-hubs-python#10]
When running the EPH against an Event Hub, I sometimes see a crash, but the log doesn't contain anything unusual, just `Segmentation fault (core dumped)` when the crash occurs.

This seems to happen more often if the EPH instance handles many partitions. An example way to reproduce is to run one instance of https://github.com/vjrantal/event-hubs-benchmarks/tree/master/python against an Event Hub with 32 partitions.

The issue might also be specific to the platform used and in my case, I was running within docker using this https://github.com/torosent/python-qpid-proton/blob/master/Dockerfile as the base image.

What I was thinking is that could this be some race condition in the Proton layer? It doesn't seem to relate to increasing memory use, because sometimes the crash happens relatively soon after the EPH has been started.

**Comment by annatisch** [comment]
The proton based implementation has now been deprecated in favor of a new uAMQP-based implementation. 
The new SDK still runs with Python bindings around a C library - so there is still the potential for such issues to occur - if you continue to encounter segmentation faults under the revised implementation, please open a new issue with details :)

Thanks!
