### ISSUE TITLE
Problem reading from IoTHub async

### ISSUE THREAD

**Issue by raghavan20** [Azure/azure-event-hubs-python#103]
I have picked up the code from examples

```
# eventhub.py

async def pump(client, partition):
    receiver = client.add_async_receiver(consumer_group, partition, offset, prefetch=5)
    await client.run_async()
    total = 0
    start_time = time.time()
    for event_data in await receiver.receive(timeout=10):
        last_offset = event_data.offset
        last_sn = event_data.sequence_number
        print("Received: {}, {}".format(last_offset.value, last_sn))
        total += 1
    end_time = time.time()
    run_time = end_time - start_time
    print("Received {} messages in {} seconds".format(total, run_time))

try:
    loop = asyncio.get_event_loop()
    client = EventHubClientAsync(address, debug=False, sas_token=sas_token)
    tasks = [
        asyncio.ensure_future(pump(client, "0")),
        # asyncio.ensure_future(pump(client, "1"))
    ]
    loop.run_until_complete(asyncio.wait(tasks))
    loop.run_until_complete(client.stop_async())
    loop.close()

except KeyboardInterrupt:
    pass
```

when i run the code with IoTHub credentials, following error is thrown

```
Task exception was never retrieved
future: <Task finished coro=<pump() done, defined at /app/eventhub.py:32> exception=AttributeError("'int' object has no attribute 'selector'",)>
Traceback (most recent call last):
  File "/app/eventhub.py", line 33, in pump
    receiver = client.add_async_receiver(consumer_group, partition, offset, prefetch=5)
  File "/app/lib/python3.6/site-packages/azure/eventhub/async_ops/__init__.py", line 202, in add_async_receiver
    keep_alive=keep_alive, auto_reconnect=auto_reconnect, loop=loop)
  File "/app/lib/python3.6/site-packages/azure/eventhub/async_ops/receiver_async.py", line 60, in __init__
    source.set_filter(self.offset.selector())
AttributeError: 'int' object has no attribute 'selector'
```

Runtime information:

-   Python: 3.6.0
-   PIP package: azure-eventhub==1.3.1

**Comment by annatisch** [comment]
Thanks @raghavan20!
Can I ask what are you setting as the initial value of `offset`?

I see if `pump()` operation, when adding the receiver an offset value is passed in:
```
async def pump(client, partition):
    receiver = client.add_async_receiver(consumer_group, partition, offset, prefetch=5)
```
This will need to be an object of type `azure.eventhub.Offset` and you can create it a variety of different ways:
```python
# Beginning of the event stream:
offset = Offset("-1")

# End of the event stream:
offset = Offset("@latest")

# Events after the specified offset:
offset = Offset("12345")

# Events from the specified offset, inclusive:
offset = Offset("12345", inclusive=True)

# Events after a datetime:
offset = Offset(datetime.datetime.utcnow())

# Events after a specific sequence number:
offset = Offset(1506968696002)
```

**Comment by raghavan20** [comment]
Thanks for pointing out. The offset was not initialized from Offset class. That problem is resolved. 

What is the ideal set of auth info to pass to `EventHubClientAsync` to work with IoTHub? 
Where can I get that information either on IoTHub UI or using Azure CLI?

**Comment by annatisch** [comment]
Thanks @raghavan20 - good to hear it's resolved :)

When using the client with IoTHub - we recommend using the iothub connection string:
`EventHubClientAsync.from_iothub_connection_string(conn_str)`

You can get this connection string from the Azure portal, under the "Shared Access Policies" in the menu, select a policy (or create a new policy with the desired permissions) and you will be presented with the connection string for that iothub.

I believe you can also get this information via the Azure CLI:
https://docs.microsoft.com/en-us/cli/azure/iot/hub/policy?view=azure-cli-latest#az-iot-hub-policy-show

**Comment by raghavan20** [comment]
I had some error building client from `EventHubClientAsync.from_iothub_connection_string`. The `_parse_conn_str` method seems to be looking for a EventHub compatible endpoint.

I used `EventHubClientAsync.from_connection_string` and it worked with the EvenHub compatible endpoint.
