### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by eavanvalkenburg** [Azure/azure-event-hubs-python#111]
Hi, this repo and all other event hub related things are all name Event Hub (with a Space, Capital, - or _) except for the Pypi package for this, which is called azure-eventhub, seems very strange and inconsistent!

**Comment by yunhaoling** [comment]
@eavanvalkenburg 

Hello Eduard, We name the package according to [Azure SDK design guidelines for Python](https://azuresdkspecs.z5.web.core.windows.net/PythonSpec.html).

In the section [Packaging](https://azuresdkspecs.z5.web.core.windows.net/PythonSpec.html#sec-packaging), one of the guidelines is: 
- DO use all lowercase in your package name with a dash (-) as a separator.

It may seem inconsistent in the Event Hub case, but we're keeping consistent across all the service sdks for python.

One more thing to mention is that we've migrated Event Hub to our [central python repo](https://github.com/Azure/azure-sdk-for-python), under [azure-sdk-for-python/sdk/eventhub/azure-eventhubs](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhubs). In the central repo, you can see how our packaging guidelines are applied.

Hope this clarifies your confusion.

**Comment by eavanvalkenburg** [comment]
ok, I see the naming but still a bit strange when the imports etc. all use EventHubs and then the package is not the event-hub that you would expect but eventhub as one word.
