### ISSUE TITLE
Issues on Windows

### ISSUE THREAD

**Issue by xinchen10** [Azure/azure-event-hubs-python#12]
The library currently does not work on Windows as is. This is due to an issue in Proton-C support for event injection on Windows.
https://issues.apache.org/jira/browse/PROTON-1071
https://issues.apache.org/jira/browse/PROTON-1692

A workaround is to apply the attached patch before building proton-c. This workaround is not an official fix, so it is not recommended to use it in production.

More details about getting it to work on Windows.
Install the following:
* Visual Studio 2015 or 2017 (make sure desktop c++ component is installed)
* Cmake (www.cmake.org)
* Swig (www.swig.org) – there is a prebuilt Windows version (32-bit only).
* Python 3.6 (32 bit) – this is important because the prebuild swig.exe is for Windows is 32-bit. Using 64-bit Python may generate OverflowError. If you build 64-bit swig, add “Win64” to the Visual Studio name (i.e. “Visual Studio 14 2015 Win64”) in the cmake command when building proton-c.

Build qpid-proton code:
* https://qpid.apache.org/proton/
* download the source from the latest release
* apply the attached patch
* follow the qpid-protoc instructions to build and install proton-c binaries
* you may need to specify `-G "Visual Studio 14 2015"` in the cmake command (change it for 2017 accordingly).

[qpid-proton-c.patch.txt](https://github.com/Azure/azure-event-hubs-python/files/1561411/qpid-proton-c.patch.txt)

**Comment by annatisch** [comment]
This should be resolved with the new uamqp based client in develop:
https://github.com/Azure/azure-event-hubs-python/tree/develop

**Comment by annatisch** [comment]
The uAMQP-based client is now merged into master and published on PyPI.
