### ISSUE TITLE
Error reconnecting (invalid offset)

### ISSUE THREAD

**Issue by olethanh** [Azure/azure-event-hubs-python#13]
Hello,

I'm using the EventHubClient connecting to 3 partitions and sometime one of the partition seem to disconnect and is unable to reconnect to  itwith the error:

`ERROR:eventhubs:eventhubs.pycli-e84eeea3: link detached name:recv-feb733f3:18788 ref:com.microsoft:argument-error dea6badf108f43539e09ccacb1ee4532_G29:The supplied offset '51541496928' is invalid. The last offset in the system is '12916091040' TrackingId:42d1ab77-24f7-4a09-81ff-78bd82e0b616_B26, SystemTracker:bpst-apim-ns-08eca:eventhub:bpst-apim-eh-08eca~24575|$default, Timestamp:12/20/2017 8:53:49 AM Reference:1060afd5-2e59-4e46-81e0-0a69b1b542e6, TrackingId:e288d8d4-4f5e-492e-bec3-ef287de5a679_B26, SystemTracker:bpst-apim-ns-08eca:eventhub:bpst-apim-eh-08eca~24575|cg-eventhub-postgres-bridge, Timestamp:12/20/2017 8:53:49 AM TrackingId:dea6badf108f43539e09ccacb1ee4532_G29, SystemTracker:gateway2, Timestamp:12/20/2017 8:53:49 AM `

Any idea why this is happening? I'm supplying an initial offset and the application is consuming messages for a few hours before this happens.

Also it seems strange that I'm seeing the '$default' consumer group appear in the log while I'm using a different one.

**Comment by xinchen10** [comment]
The client keeps track of the offset of the last received event and uses that to reopen the link on failures. I need to take a look at the service side logs to understand why the service thinks the offset has changed. The error message contains information from multiple components so the $default consumer group name might be just an error tracking issue.

**Comment by xinchen10** [comment]
@olethanh Service was delivering correct messages. It seems that the offset kept on the client was wrong.

How did you read the events? Can you share the code here? Is it possible that you subscribe the same Receiver object to all 3 partitions? The client stores the last offset in the receiver so it can go wrong if all three pumps try to update the same offset. I will add a check in the subscribe method to disallow a receiver to be registered more than once.

**Comment by olethanh** [comment]
Yes I'm subscribing the same receivers, wasn't aware it wasn't a supported use case.
