### ISSUE TITLE
EPH fails silently in case of bad credentials

### ISSUE THREAD

**Issue by itamarla** [Azure/azure-event-hubs-python#14]
When trying to open_async() an EPH using bad credentials (e.g. bad SAS policy key) the EPH exits with an exception that doesn't imply anything about a credentials related issue. 
Authentication failure should generate some logs with relevant information or/and raise a relevant exception.

**Comment by xinchen10** [comment]
We are improving error handling and logging/diagnostics in the client.

**Comment by annatisch** [comment]
I've confirms that this doesn't happen with release 0.2.0rc1
