### ISSUE TITLE
Publish this to pypi for pip installations, and docker to dockerhub.

### ISSUE THREAD

**Issue by AXington** [Azure/azure-event-hubs-python#20]
I'd like to be able to use this without having to clone the whole library or adding it as a submodule. Right now, i'm running it in a docker, and I'm building two images, the one in /examples with some very minor changes, and then using that as a base image for my code. Really, I should either just be pulling an official image from dockerhub, or installing with pypi instead of building that base image.

**Comment by Ram9293** [comment]
Hi AXington, I am having trouble with creating the image that is in examples, could you please share the changes so that I can use those changes. Thank you..!

**Comment by AXington** [comment]
@Ram9293 

My changes are product specific changes. If you're having trouble building the image, then you should open another support ticket.

If you do, I will be happy to help you with general docker questions. Which, likely if you're having trouble, that's your problem because there's nothing special or different about the example docker image.

**Comment by xinchen10** [comment]
We are making some major changes to the client (mainly the underlying amqp library) to improve build and deployment experience and provide a working solution for Windows. pypi support will come as part of this work.

**Comment by annatisch** [comment]
The [new preview library](https://github.com/Azure/azure-event-hubs-python/tree/develop) is now published on PyPI - though please note that it has a few breaking changes from the previous client in master.
https://pypi.org/project/azure-eventhub/
