### ISSUE TITLE
Partition key cannot be set for events

### ISSUE THREAD

**Issue by halldorbjarni** [Azure/azure-event-hubs-python#25]
When trying to set a partition key for the EventData object with `event_data.partition_key = 'some-guid'` it results in an Exception since the message.annotations dictionary is never declared for the EventData object.  Proton expects the whole annotations dictionary as an argument to the Message constructor. 

Even with fixing that, messages are randomly partitioned and on closer inspection the messages do not have a partition key set in Service Bus Explorer. When looking at the AMQP frame trace for the sender it seems to contain x-opt-partition-key. Any idea what might be wrong?

**Comment by annatisch** [comment]
This has been fixed in the 0.2.0b2 release.
