### ISSUE TITLE
Get events from multiple partitions using azure-event-hubs-python?

### ISSUE THREAD

**Issue by sachin-aryal** [Azure/azure-event-hubs-python#27]
I tried creating multiple receivers for different partition but failed as a **run()** method seems to be blocking one. I tried something like this
```
for partition in range(0, 4):
    EventHubClient(ADDRESS).subscribe(MyReceiver(str(partition)), CONSUMER_GROUP, str(partition), OFFSET).run()
```

But it only creates a receiver for Partition 0 and listens to it only. Is there any simple way to create multiple receivers that listen to the event on the different partition.

I also tried using

```
for partition in range(0, 4):
    EventHubClient(ADDRESS).subscribe(MyReceiver(str(partition)), CONSUMER_GROUP, str(partition), OFFSET).run_daemon()
```
It created multiple receiver, but I did not actually got the data.

**Comment by xinchen10** [comment]
The run method is blocking so you will only get events from the first partition. You can do the following to subscribe to multiple partitions.
```
EventHubClient(ADDRESS).subscribe(MyReceiver("0"), CONSUMER_GROUP, "0", OFFSET)
    .subscribe(MyReceiver("1"), CONSUMER_GROUP, "1", OFFSET)
    .subscribe(MyReceiver("2"), CONSUMER_GROUP, "2", OFFSET)
    .subscribe(MyReceiver("3"), CONSUMER_GROUP, "3", OFFSET)
    .run()
```

If you can run_daemon, you will need to call receive on each receiver in a loop to get events.

**Comment by sachin-aryal** [comment]
Thank you, I tried and It worked.
