### ISSUE TITLE
IoT Hub support

### ISSUE THREAD

**Issue by ngunderson** [Azure/azure-event-hubs-python#28]
I am having trouble setting up this SDK to be used to receive events from an IoT Hub. I cannot seem to format the EventHubClient Address correctly. Is this possible, I'm just formatting something wrong?

I get the following error:

`ERROR    eventhubs.pycli-56f1941f: transport close, condition Condition('proton:io:sasl_error', 'SASL(-4): no mechanism available: No worthy mechs found (Authentication failed [mech=none])')`

My ADDRESS, as in the example, is formatted as the following:

`"amqps://iothubowner:<mySASkey>@<broker-name>.azure-devices.net/`

**Comment by ngunderson** [comment]
I can keep a connection open if I use `amqp` instead of `amqps`. However, I still cannot receive messages. I also tried adding `/messages/events` to the end of my ADDRESS. Any other ideas?

**Comment by xinchen10** [comment]
The library does not support IoT Hub.

**Comment by ngunderson** [comment]
I know see that it's mentioned here that "Event Hubs does not support telemetry in Python yet". (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-getstarted#receive-messages-from-your-simulated-device).

**Comment by annatisch** [comment]
@ngunderson  IoT hub have their own specific Python client library:
https://pypi.org/project/azure-iothub-device-client/

Is there a particular reason you're not using this one?

**Comment by ngunderson** [comment]
So this code is running on a webapp I am writing, not a device. I want to receive any events that are sent from my device (Arduino) to the IoT hub on the server in realtime. The device client doesn't allow this functionality.

**Comment by annatisch** [comment]
Thanks @ngunderson,
I'll do some tests to see if I can get this scenario working under the preview client under development in the [develop branch](https://github.com/Azure/azure-event-hubs-python/tree/develop) (also now released on [PyPI](https://pypi.org/project/azure-eventhub/)).

If this scenario isn't supported with the eventhub SDK, then we might be able to support it by working directly against [the AMQP layer](https://github.com/azure/azure-uamqp-python).

**Comment by annatisch** [comment]
This has been partially resolved in the 0.2.0b2 release - the device ID annotation is now exposed on the EventData object as an attribute called `device_id`.
We are also working on resolving the automatic IoTHub - > EventHub URL redirect - though this will take a little longer, it should be ready for the next release.

**Comment by Arohdin** [comment]
Hi

I am having problems to regarding the 'Event Hub-compatible endpoint' with my IoT device.
On my case, however, I do seem to be able to connect without appending the _path_ property. Actually, if I add the path property mentioned in @annatisch 's post I get the following errors (I use the async receiver provided in the python samples):

` ... Status code: 404 `

` ... The messaging entity 'sb://<ENDPOINT-NAME>.servicebus.windows.net/<IOT-DEVICE-NAME> could not be found. TrackingId:<TRACKING ID>, SystemTracker:<ENDPOINT-NAME>.servicebus.windows.net:<ENDPOINT-NAME>, Timestamp:6/13/2018 2:03:09 PM`


If I leave out the path property I seem to find the endpoint, but I get this error instead:

`Authentication Put-Token failed. Retries exhausted.`

` ...exception=EventHubError("Receive failed: CBS Token authentication failed.\nStatus code: 401\nDescription: b'InvalidSignature: The token has an invalid signature. TrackingId:<TRACKING ID>, SystemTracker:NoSystemTracker, Timestamp:6/13/2018 2:09:02 PM`

`...uamqp.errors.TokenAuthFailure: CBS Token authentication failed.`
`Status code: 401`

`...azure.eventhub.EventHubError: Receive failed: CBS Token authentication failed.`


Any ideas?
I've tried using the `EventHubClient.from_connection_string()` function too, but I get the same error as first described.

Also, I skipped a lot of the error output. Basically it's just a lot of tracebacks. If that is interesting to see, please tell me and I'll upload the whole log.

**Comment by Arohdin** [comment]
Hi

I am having problems to regarding the 'Event Hub-compatible endpoint' with my IoT device.
On my case, however, I do seem to be able to connect without appending the _path_ property. Actually, if I add the path property mentioned in @annatisch 's post I get the following errors (I use the async receiver provided in the python samples):

` ... Status code: 404 `

` ... The messaging entity 'sb://<NAMESPACE>.servicebus.windows.net/<IOT-DEVICE-NAME> could not be found. TrackingId:<TRACKING ID>, SystemTracker:<NAMESPACE>.servicebus.windows.net:<IOT-DEVICE-NAME>, Timestamp:6/13/2018 2:03:09 PM`


If I leave out the path property I seem to find the endpoint, but I get this error instead:

`Authentication Put-Token failed. Retries exhausted.`

` ...exception=EventHubError("Receive failed: CBS Token authentication failed.\nStatus code: 401\nDescription: b'InvalidSignature: The token has an invalid signature. TrackingId:<TRACKING ID>, SystemTracker:NoSystemTracker, Timestamp:6/13/2018 2:09:02 PM`

`...uamqp.errors.TokenAuthFailure: CBS Token authentication failed.`
`Status code: 401`

`...azure.eventhub.EventHubError: Receive failed: CBS Token authentication failed.`

The interesting part is that it did work, once, and then I got the authentication error again...

Any ideas?
I've tried using the `EventHubClient.from_connection_string()` function too, but I get the same error as first described.

Also, I skipped a lot of the error output. Basically it's just a lot of tracebacks. If that is interesting to see, please tell me and I'll upload the whole log.

**Comment by annatisch** [comment]
Thanks @Arohdin! 
Can I confirm whether you're attempting to send or receive messages?
I believe the above workarounds were only tested when receiving.

As it happens I've been working on proper IoTHub support - the SDK _should_ be able to take the IoTHub connection string from the portal and connect with that, but in order to work properly the client must be able to handle a redirect response from the service (a redirect from the IoThub endpint to the eventhub endpoint). Progress for this fix is being tracked here and once it's complete I'll update the EventHub SDK with all the necessary helpers to work with IoTHub:
https://github.com/Azure/azure-uamqp-c/issues/231

**Comment by Arohdin** [comment]
Thanks for the quick response.
Just to be on the safe side and double check everything, am I using the right username and password?

The username is my the 'shared access policies' 'iothubowner'; which is also the 'SharedAccessKeyName' from the 'Event Hub-compatible endpoint'.
The password was retrieved from the value 'SharedAccessKey' in the 'Event Hub-compatible endpoint'.

**Comment by annatisch** [comment]
Thanks for the update @Arohdin!
I wont close this issue until I have proper handling for redirecting from the IoThub connection string to the equivalent EventHub connection string.

**Comment by annatisch** [comment]
Thanks for your patience @ngunderson and @Arohdin, connecting to an IoThub is now fully supported as of release 0.2.0rc1.
So examples of how to do this see:
- [Sending to IotHub](https://github.com/Azure/azure-event-hubs-python/blob/master/tests/test_iothub_send.py)
- [Receiving from IoTHub](https://github.com/Azure/azure-event-hubs-python/blob/master/tests/test_iothub_receive.py)
- [Receiving from IoTHub asynchronously with multiple receivers](https://github.com/Azure/azure-event-hubs-python/blob/master/tests/test_iothub_receive_async.py)

If you encounter any difficulties please open up fresh issues as needed. :)

**Comment by Fenn-CS** [comment]
Lucky am arriving at the very just to rip fruits! Hope all goes well! Great work @annatisch

**Comment by theamrzaki** [comment]
I have tried running this as my reciever
`#!/usr/bin/env python

# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

"""
An example to show receiving events from an Event Hub partition.
"""
import os
import sys
import logging
import time
from azure.eventhub import EventHubClient, Receiver, Offset

# Address can be in either of these formats:
# "amqps://<URL-encoded-SAS-policy>:<URL-encoded-SAS-key>@<mynamespace>.servicebus.windows.net/myeventhub"
# "amqps://<mynamespace>.servicebus.windows.net/myeventhub"
ADDRESS ="amqps://iothub-ns-virtualab2-926709-043cc22e89.servicebus.windows.net/virtualab2"

# SAS policy and key are not required if they are encoded in the URL
USER = "iothubowner"
KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CONSUMER_GROUP = "teststream"
OFFSET = Offset("-1")
PARTITION = "1"


total = 0
last_sn = -1
last_offset = "-1"
client = EventHubClient(ADDRESS, debug=True, username=USER, password=KEY)

try:
    receiver = client.add_receiver(CONSUMER_GROUP, PARTITION, prefetch=5000, offset=OFFSET)
    client.run()
    print("client connected")
    start_time = time.time()
    print("listening")
    batch = receiver.receive(timeout=5000)
    
    while batch:
        for event_data in batch:
            last_offset = event_data.offset
            last_sn = event_data.sequence_number
            print("Received: {}, {}".format(last_offset.value, last_sn))
            print(event_data.body_as_str())
            total += 1
        batch = receiver.receive(timeout=5000)

    end_time = time.time()
    client.stop()
    run_time = end_time - start_time
    print("Received {} messages in {} seconds".format(total, run_time))

except KeyboardInterrupt:
    pass
finally:
    client.stop()
`
it connects , but never listens 
my sender is the same as that of the quickstart from azure tutorial 

please help

**Comment by annatisch** [comment]
Hi @theamrzaki - this issue has long since been closed.
Please open a new issue and post the details there along with:
- Python version used
- Versions of both azure-eventhub and uamqp libraries
- Operating system used
- If possible a debug trace
