### ISSUE TITLE
UAMQP Install breaks

### ISSUE THREAD

**Issue by slyons** [Azure/azure-event-hubs-python#36]
When installing any build after UAMQP was introduced it generates an error on install:

```
Collecting uamqp~=0.1.0b4 (from azure-eventhub==0.2.0b1)
  Using cached https://files.pythonhosted.org/packages/dd/12/84c134e8676526ec73c4748ed4ed659743aad828fe9dee150941d495831b/uamqp-0.1.0rc1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s1/8bpsbms13n97yzt2d45gcgkh0000gn/T/pip-install-ktcsUT/uamqp/setup.py", line 207, in <module>
        UAMQPExtension("cmake_uamqp"),
      File "/private/var/folders/s1/8bpsbms13n97yzt2d45gcgkh0000gn/T/pip-install-ktcsUT/uamqp/setup.py", line 92, in __init__
        super(UAMQPExtension, self).__init__(name, sources=[])
    TypeError: super() argument 1 must be type, not classobj
```

**Comment by annatisch** [comment]
@slyons - Thanks for this! I will investigate ASAP.

**Comment by annatisch** [comment]
@lmazuel - do have any thoughts on how the [uamqp setup.py](https://github.com/Azure/azure-uamqp-python/blob/master/setup.py) could be having an affect on other packages?

**Comment by lmazuel** [comment]
This pip installation is using the sdist, not the wheel (see trace). Also, the exception implies setuptools version does not match that version we used to develop the setup.py.
So my guess is that the pip/setuptools env is old, and we require more recent one to make it work. Two possible fix here:
- We investigate older version of setuptools and make the setup.py resilient
- We just say that we support installation starting setuptools X.Y.Z (TBD)

**Comment by annatisch** [comment]
@slyons - could you confirm whether you are installing the azure-eventhub package with Python 2.7?

**Comment by annatisch** [comment]
I've removed Python 2 support from the wheel of the RC1 release.
I will open a new issue for adding Python 2 support to the library in general.
