### ISSUE TITLE
Installation problem on Ubuntu

### ISSUE THREAD

**Issue by cezane** [Azure/azure-event-hubs-python#37]
I am having problems with the azure event hubs sdk installation process on Ubuntu. As recommended, I installed Proton-C and all the needed dependencies:

    libs: libxml2-dev, libxslt-dev, libffi-dev, python3-cffi
    Python packages: requests, bs4, lxml, azure-storage, azure-storage-blob

Then, I have to find out on the net the name of the event hub module to install: azure-eventhub (without s; the documentation does not mention that). I tried to install pip install azure-eventhub, but I got:

    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-FiT0ef/uamqp/

Then, after more search, I guess it can be because the Python 2.7 version is not supported. So, I installed with pip3 install azure-eventhub. But, yet, I can not import the module as in this example: https://github.com/Azure/azure-event-hubs-python/blob/master/examples/recv.py

Could you please clarify these points? Am I missing something else? I think these documentations could be really improved...

Thank you.

**Comment by annatisch** [comment]
Hi @cezane - there are currently two different versions of the EventHubs SDK:
- One based on Proton, this has now been deprecated.
- A new library based on uAMQP. This is the one installed in the package azure-eventhub on PyPI.

While the two different implementations have much in common - there are major braking changes between them, so the examples provided for the Proton implementation will not work for the uAMQP implementation and vice-versa.

I have just merged the uAMQP implementation from the develop branch into master. Now the examples in master should run under the package installed in pip:
https://github.com/Azure/azure-event-hubs-python/blob/master/examples/recv.py

I quite agree that the documentation is still lacking. We hope to have the reference docs for the SDK published soon (within the next week hopefully) with more samples, articles and tutorials to follow.

Let me know how it goes!

**Comment by annatisch** [comment]
Hi @cezane - I'm going to close this - feel free to reopen if you're still having trouble. :)

**Comment by det-iot** [comment]
Hello,

Is this problem solved? I have the same issue (using python 3.7 and 2.7) with this code:

https://github.com/Azure/azure-event-hubs-python/blob/master/examples/recv.py

**Comment by annatisch** [comment]
Hi @det-iot  - which version of the Azure EventHubs SDK for Python are you running?

**Comment by det-iot** [comment]
Hi @annatisch i'm using azure-eventhub 1.2.0
