### ISSUE TITLE
installation issue on Mac

### ISSUE THREAD

**Issue by vishleshpatel** [Azure/azure-event-hubs-python#38]
~ > pip install azure-eventhub
Collecting azure-eventhub
  Using cached https://files.pythonhosted.org/packages/57/ea/469f3e82113a51da78aa58a811aa437f0bfc6fb47c391ea1f0b8f78731fa/azure_eventhub-0.2.0b2-py2.py3-none-any.whl
Requirement already satisfied: azure-common~=1.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from azure-eventhub) (1.1.8)
Requirement already satisfied: msrestazure~=0.4.11 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from azure-eventhub) (0.4.22)
Collecting azure-storage~=0.36.0 (from azure-eventhub)
  Using cached https://files.pythonhosted.org/packages/76/26/482c033f8f3a48d16cf75aad91c3e1256856719f4117fabb4696d33aa5da/azure_storage-0.36.0-py2.py3-none-any.whl
Collecting uamqp~=0.1.0rc1 (from azure-eventhub)
  Using cached https://files.pythonhosted.org/packages/dd/12/84c134e8676526ec73c4748ed4ed659743aad828fe9dee150941d495831b/uamqp-0.1.0rc1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tx/v8mw27js4vn1rzwr53dxf1y400cynn/T/pip-install-z6mOHC/uamqp/setup.py", line 207, in <module>
        UAMQPExtension("cmake_uamqp"),
      File "/private/var/folders/tx/v8mw27js4vn1rzwr53dxf1y400cynn/T/pip-install-z6mOHC/uamqp/setup.py", line 92, in __init__
        super(UAMQPExtension, self).__init__(name, sources=[])
    TypeError: super() argument 1 must be type, not classobj
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tx/v8mw27js4vn1rzwr53dxf1y400cynn/T/pip-install-z6mOHC/uamqp/
~>

**Comment by annatisch** [comment]
Thanks @vishleshpatel - could you confirm which version of setuptools you are using?

**Comment by vishleshp** [comment]
Thanks for the response @annatisch ..

it's 39.2.0

~/> easy_install --version
setuptools 39.2.0 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (Python 2.7)

**Comment by annatisch** [comment]
Thanks @vishleshpatel - It may because Python 2.7 is not supported by the underlying uAMQP library. Can you confirm whether you are installing using Python 2.7?

**Comment by vishleshp** [comment]
I have python 2.7 and 3 both installed on my Mac. Not sure which version pip is using to install this package. 

However, if python3 is requirement, I think it shall be mentioned in ReadMe.

**Comment by annatisch** [comment]
Thanks @vishleshp!
I've removed Python 2 support from the wheel of the RC1 release.
I will open a new issue for adding Python 2 support to the library in general.
