### ISSUE TITLE
Can the event processor host work from behind a proxy

### ISSUE THREAD

**Issue by ahtpatel** [Azure/azure-event-hubs-python#41]

**Comment by annatisch** [comment]
Currently no - this is not supported. Will add it to the wish list :)

**Comment by annatisch** [comment]
Added issue to uAMQP: https://github.com/Azure/azure-uamqp-python/issues/25

**Comment by ahtpatel** [comment]
@annatisch - Thanks for looking into this.

**Comment by annatisch** [comment]
Support for this has now been added in [RC2](https://github.com/Azure/azure-event-hubs-python/releases/tag/v0.2.0rc2).
You can pass proxy settings to both the SDK and EPH. The settings must be in a dictionary, with two mandatory keys `"proxy_hostname"` (a string value) and `"proxy_port"` (an integer value). You can also set optional keys `"username"` and `"password"`.
Example:
```
proxy_settings = {
    "proxy_hostname": "127.0.0.1",
    "proxy_port": 12345,
    "username": "my_proxy_credentials",
    "password": "******"
}
```

You can pass these settings to the SDK client:
`eh_client = azure.eventhub.EventHubClient.from_connection_string(conn_str, http_proxy=proxy_settings)`

And to use with EPH, you can set it on the Options object:
```
options = azure.eventprocessorhost.EPHOptions()
options.http_proxy = proxy_settings
client = azure.eventprocessorhost.EventProcessorHost(
    MyProcessorHost,
    my_config,
    my_storage_manager,
    eh_options=options
)
