### ISSUE TITLE
How to specify newest message on Options.initial_offset_provider?

### ISSUE THREAD

**Issue by KevinKao809** [Azure/azure-event-hubs-python#57]
ehOptions = EPHOptions()
ehOptions.receive_timeout = 300
ehOptions.keep_alive_interval = 290
ehOptions.release_pump_on_timeout = False
ehOptions.initial_offset_provider =                    
ehOptions.debug_trace = False

**Comment by annatisch** [comment]
Thanks @KevinKao809 - you can select only the latest messages like so:
`ehOptions.initial_offset_provider = '@latest'`

Or you can do from the current timestamp:
`ehOptions.initial_offset_provider = datetime.datetime.utcnow()`
