### ISSUE TITLE
Shut down eventprocessorhost and the underlying loop iif all its partitions received no messages for 1 hour.

### ISSUE THREAD

**Issue by grantzvolsky** [Azure/azure-event-hubs-python#59]
I hope it is clear from the title what I would like to achieve. Is it possible using the current API?

**Comment by annatisch** [comment]
Thanks @grantzvolsky - I will try to replicate your scenario and report back :)

**Comment by annatisch** [comment]
Hi again, in short yes :)
The following snippets are based on the existing EPH sample here: 
https://github.com/Azure/azure-event-hubs-python/blob/master/examples/eph.py

First we want to modify the settings to raise a timeout error if no messages are received in an hour:
```
eh_options = EPHOptions()
eh_options.release_pump_on_timeout = True
eh_options.receive_timeout = 3600
```

Next we want to capture the timeout errors and store those against a particular partition. In this case I will use a simple `partition_states` dictionary to store the partition timeouts and pass this to my EventProcessHost.
```
partition_states = {}

# Event loop and host
host = EventProcessorHost(
    EventProcessor,
    eh_config,
    storage_manager,
    eph_options=eh_options,
    ep_params=partition_states,
    loop=loop)
```

In my EventProcessorHost implementation, I can then store the timeout errors against the partition ID, and clear them when new messages arrive:
```
class EventProcessor(AbstractEventProcessor):

    def __init__(self, partition_states):
        super().__init__(partition_states)
        self._partitions = partition_states

    async def open_async(self, context):
        logger.info("Connection established {}".format(context.partition_id))
        if not self._partitions.get(context.partition_id):
            self._partitions[context.partition_id] = 'STARTED'

    async def close_async(self, context, reason):
        logger.info("Connection closed (reason {}, id {}, offset {}, sq_number {})".format(
            reason,
            context.partition_id,
            context.offset,
            context.sequence_number))

    async def process_events_async(self, context, messages):
        self._partitions[context.partition_id] = 'RECEIVING'
        print("Processing id {}, offset {}, sq_number {})".format(
            context.partition_id,
            context.offset,
            context.sequence_number))
        await context.checkpoint_async()

    async def process_error_async(self, context, error):
        logger.info("Event Processor Error for partition {}, {!r}".format(context.partition_id, error))
        if isinstance(error, TimeoutError):
            logger.info("No Events for partition {} in an hour. Shutting down.".format(context.partition_id))
            self._partitions[context.partition_id] = 'TIMEOUT'
```

Any finally, the last step is to monitor these partition states and if every partition is in a state of timeout, shut down the host:
```
async def wait_and_close(host, partition_states):
    await asyncio.sleep(30)
    while partition_states and not all([s == 'TIMEOUT' for s in partition_states.values()]):
        logger.info("Partition states: {}".format(partition_states))
        await asyncio.sleep(10)
    logger.error("All partitions have timed out. Shutting down EPH.")
    await host.close_async()

tasks = asyncio.gather(
   host.open_async(),
   wait_and_close(host, partition_states), return_exceptions=True)
results = loop.run_until_complete(tasks)
```
You can then shut down the event loop on completion. :)

There would be other ways to do this, but hopefully this demonstrates some of the ways you can manipulate EPH. 

Thanks!

**Comment by grantzvolsky** [comment]
Thank you very much, it works flawlessly! I have just one additional question: wouldn't it cover the force-detached-from-service scenario if we added the following lines to close_async?

```
  if self._partitions.get(context.partition_id):
    del self._partitions[context.partition_id]
```

**Comment by annatisch** [comment]
Good to hear it's working @grantzvolsky!

Not quite - as the issue is more to do with timing - as the partition once detached will simply be restarted and will attempt to retrieve with no memory that it had already waited for 45 minutes without receiving a message before it was detached.

What you could try - instead of storing an arbitrary string ('STARTED', 'TIMEOUT' etc), you could store the 'last activity timestamp' (i.e. `datetime.datetime.now()`) each time a message is received. Then whenever a partition is started/closed/errored - the state would not impact the absolute timestamp for when that partition actually handled event data.

Then you could simply make some adjustments to the `wait_and_close` function to monitor the activity timestamps and when no partition has a timestamp from the last hour it could be shutdown.

This would handle any errors/restarts/detach scenarios :)

Thanks!
