### ISSUE TITLE
AzureStorageCheckpointLeaseManager should take container sas token rather then account key 

### ISSUE THREAD

**Issue by ahtpatel** [Azure/azure-event-hubs-python#61]
In the code below AzureStorageCheckpointLeaseManager should take lease container sas token rather than the account key as account key provides authorization for the entire storage account. Or at least have sas token as an option.

```
storage_manager = AzureStorageCheckpointLeaseManager(
        STORAGE_ACCOUNT_NAME, STORAGE_KEY, LEASE_CONTAINER_NAME)
```

**Comment by annatisch** [comment]
Sure I can add this - thanks @ahtpatel  :)

**Comment by annatisch** [comment]
I have added storage account SAS token support, as well the option to configure the endpoint suffix (for National Clouds) and support for configuring via connection string.

I will get these changes published this week.
Thank you for your patience!

**Comment by annatisch** [comment]
Thanks @ahtpatel - I have now added a number of new configuration options to the AzureStorageCheckpointLeaseManager class in v1.1.0 - including:

  - The `storage_account_name`, `storage_account_key` and `lease_container_name` arguments are now optional keyword arguments.
  - Added a `sas_token` argument that must be specified with `storage_account_name` in place of `storage_account_key`.
  - Added an `endpoint_suffix` argument to support storage endpoints in National Clouds.
  - Added a `connection_string` argument that, if specified, overrides all other endpoint arguments.
  - The `lease_container_name` argument now defaults to `"eph-leases"` if not specified.
