### ISSUE TITLE
How do we actually read the data from IoT Hub?

### ISSUE THREAD

**Issue by MZein1292** [Azure/azure-event-hubs-python#71]
Thank you for adding IoT Hub support recently!

I am running the `rcv.py` example and I am expecting to be able to read the messages sent to the event hub, but I am confused on what the `last_offset` and `last_sn` are in the examples, and confused on how to actually read the data.

```
from azure.eventhub import EventHubClient, Receiver, Offset

iot_hub_conenction_string = "myconnectionstring"

client = EventHubClient.from_iothub_connection_string(iot_hub_conenction_string, debug=True)
receiver = client.add_receiver("myconsumergroup", "0", operation='/messages/events')
try:
    client.run()
    partitions = client.get_eventhub_info()
    print(partitions)
    while True:
        for event_data in receiver.receive():
            last_offset = event_data.offset
            last_sn = event_data.sequence_number
            print("Received: {}, {}".format(last_offset.value, last_sn))
            print(event_data.message)  // prints byte data
finally:
    client.stop()
```

From my example when I try to print `event_data.message` I get bytes or an encoded message in the console.

Am I missing something? And how do I actually read the data?

Thanks for the help!

**Comment by annatisch** [comment]
Hi @MZein1292 - thanks for your question!

Depending on the format of the data in your events, there are two helper functions on the EventData object:
- [event_data.body_as_str()](https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub.common.eventdata?view=azure-python#body-as-str)
- [event_data.body_as_json()](https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub.common.eventdata?view=azure-python#body-as-json)


Hopefully this helps! :)

**Comment by MZein1292** [comment]
@annatisch thank you for responding

I tried both and this is what I got:

```
  File "C:\Python27\lib\site-packages\azure\eventhub\common.py", line 230, in body_as_json
    data_str = self.body_as_str(encoding=encoding)
  File "C:\Python27\lib\site-packages\azure\eventhub\common.py", line 220, in body_as_str
    raise TypeError("Message data is not compatible with string type: {}".format(e))
TypeError: Message data is not compatible with string type: 'generator' object has no attribute 'decode'
```

**Comment by MZein1292** [comment]
Hi @annatisch thank you for 

I have tried both and I got this error, I tried with and without the encoding parameter. 

```
Traceback (most recent call last):
  File "rcv.py", line 22, in <module>
    print(event_data.body_as_json(encoding='UTF-8'))
  File "C:\Python27\lib\site-packages\azure\eventhub\common.py", line 230, in body_as_json
    data_str = self.body_as_str(encoding=encoding)
  File "C:\Python27\lib\site-packages\azure\eventhub\common.py", line 220, in body_as_str
    raise TypeError("Message data is not compatible with string type: {}".format(e))
TypeError: Message data is not compatible with string type: 'generator' object has no attribute 'decode'
```

Am I trying to decode the message incorrectly?

**Comment by annatisch** [comment]
Thanks @MZein1292 - hmm that's interesting - I will investigate that error.

In the meantime you should still be able to get the data directly from the [message body](https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub.common.eventdata?view=azure-python#body):
```
data = list(event_data.body) # Depending on the contents of your message, this will likely be a list of bytes - inspect to confirm.
bytes_data = b"".join(data)  # Combine the data into a single string
str_data = bytes_data.decode(encoding)  # Encoding here is typically UTF-8 but would also depend on your data source.
```

**Comment by MZein1292** [comment]
@annatisch I am not sure if this is related to the package

When sending data using IotHubMessage I am not encoding it in `UTF-8` 
https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_sample.py#L210

So when trying to decode it in the receiver I get this error:

`UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 7: invalid continuation byte`

Without the encoding it prints the bytes normally (but no string). 

i tried to produce the data it in bytearray and UTF-8 from IoTHubMessage 
https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_sample.py#L208

But still getting the same error. So unfortunately this did not work as well.

```
    while True:
        for event_data in receiver.receive():
            last_offset = event_data.offset
            last_sn = event_data.sequence_number
            data = list(event_data.body) 
            bytes_data = b"".join(data) 
            str_data = bytes_data.decode('utf-8')  # DOES NOT WORK :(
            print(str_data)
```

**Comment by annatisch** [comment]
Ah... okay - yes that's certainly not utf-8.
It looks like there will need to be some kind of proprietary decoding process.... do you know what the content of this data is supposed to be?

**Comment by MZein1292** [comment]
Python version: 2.7.13

EventHub SDK: 1.2.0rc1

Well initially I was sending protobuf messages (Which I understand would need to be deserialized) but I changed that today to a simple string

```
message_azure = IoTHubMessage("hello")
client.send_event_async(message_azure, send_confirmation_callback, None)
```

I don't know if it's somehow reading old messages but I have not sent protobuf messages since yesterday, so I assume it is not the case.

**Comment by annatisch** [comment]
Thanks @MZein1292 - is it possible that those earlier protobuf messages are still sitting in the EventHub? 
What did you set as the message expiry time for the iothub?

You could try doing a try/except on the bytes.decode() line and just continuing to receive to see if later messages start coming through as strings?
Alternaitvely you could start the receiver with a [timestamp based offset](https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub.common.offset?view=azure-python) so that it will not receive any messages older than today.

**Comment by MZein1292** [comment]
@annatisch You were correct about old messages still sitting in Event Hub, printing the enqueued time it showed messages from yesterday. And the try/except printed out the strings that were sent today.  Feel free to close this since it solves my problem in reading messages. 

Thank you for the help!

**Comment by MZein1292** [comment]
Quick question: Do you have an example somewhere for setting a timestamp based offset to the receiver?

**Comment by annatisch** [comment]
Great news @MZein1292!

If you click the offset documentation I linked to above you can see how to initialize an Offset using a datetime object. Additionally you can see how it can be used in my tests here:
https://github.com/Azure/azure-event-hubs-python/blob/master/tests/test_receive.py#L35

PS. Thank you so much for testing out the release candidate on Python 2.7!
