### ISSUE TITLE
Read IoT Hub events using python

### ISSUE THREAD

**Issue by jasanchezizertis** [Azure/azure-event-hubs-python#75]
Hi, 
I am trying to read messages from the IoT Hub using the python version of azure event hub.

Event Hub-compatible name and Event Hub-compatible endpoint are:

Event Hub-compatible name: sysmloud-iothub-operationmonitoring
Event Hub-compatible endpoint: Endpoint=sb://iothub-ns-sysmloud-i-621977-9d0e7c8adf.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx= 

The code to read the Iot Hub events is the following:   

import os
import sys
import logging
import time
from azure.eventhub import EventHubClient, Receiver, Offset

PARTITION = "0"

total = 0
last_sn = -1
last_offset = "-1"

 
iot_connection_str = 'Endpoint=iothub-ns-sysmloud-i-621977-9d0e7c8adf.servicebus.windows.net/sysmloud-iothub-operationmonitoring;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx='

client = EventHubClient.from_iothub_connection_string(iot_connection_str, debug=True)

try:
    receiver = client.add_receiver("$default", PARTITION,operation='/message/events')
    client.run()
    partitions = client.get_eventhub_info()
    print(partitions)
    start_time = time.time()
    for event_data in receiver.receive(timeout=100):
        last_offset = event_data.offset
        last_sn = event_data.sequence_number
        print("Received: {}, {}".format(last_offset, last_sn))
        total += 1

    end_time = time.time()
    client.stop()
    run_time = end_time - start_time
    print("Received {} messages in {} seconds".format(total, run_time))

except KeyboardInterrupt:
    pass
finally:
    client.stop()
	
	
I am getting this error:

LinkDetach('ErrorCodes.NotAllowed: Invalid EventHub address. It must be either of the following. Sender: <EventHubName>. Partition Sender: <EventHubName>/Partitions/<PartitionNumber>. Partition Receiver: <EventHubName>/ConsumerGroups/<ConsumerGroupName>/Partitions/<PartitionNumber>. TrackingId:5634e3b4a0234501be524990955ab408_G8, SystemTracker:gateway5, Timestamp:10/25/2018 10:11:34 AM',)
'eventhub.pysdk-a0b14d04': All clients failed to start.

I tried different combinations of iot connection strings with no luck. 

Can you please help me?

Thank you!!

Regards.

**Comment by annatisch** [comment]
Thanks for the report @jasanchezizertis!
When creating an EventHub client using the `from_iothub_connection_string` you should not have to use the "EventHub compatible endpoint", rather just pass in the standard IotHub connection string, that will probably be in the format: 
```
"HostName=sysmloud.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxx="
```

If you wish to use the "EventHub compatible endpoint" you can create the EventHub client object using the standard `from_connection_string` class method.

Let me know how it goes! :)

**Comment by annatisch** [comment]
Good to hear! :)
