### ISSUE TITLE
event hub connects , but doesn't recieve mmessages

### ISSUE THREAD

**Issue by theamrzaki** [Azure/azure-event-hubs-python#78]
I have tried running this as my reciever

```
import os
import sys
import logging
import time
from azure.eventhub import EventHubClient, Receiver, Offset

Address can be in either of these formats:
"amqps://:@.servicebus.windows.net/myeventhub"
"amqps://.servicebus.windows.net/myeventhub"
ADDRESS ="amqps://iothub-ns-virtualab2-926709-043cc22e89.servicebus.windows.net/virtualab2"

SAS policy and key are not required if they are encoded in the URL
USER = "iothubowner"
KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
CONSUMER_GROUP = "teststream"
OFFSET = Offset("-1")
PARTITION = "1"

total = 0
last_sn = -1
last_offset = "-1"
client = EventHubClient(ADDRESS, debug=True, username=USER, password=KEY)

try:
receiver = client.add_receiver(CONSUMER_GROUP, PARTITION, prefetch=5000, offset=OFFSET)
client.run()
print("client connected")
start_time = time.time()
print("listening")
batch = receiver.receive(timeout=5000)

while batch:
    for event_data in batch:
        last_offset = event_data.offset
        last_sn = event_data.sequence_number
        print("Received: {}, {}".format(last_offset.value, last_sn))
        print(event_data.body_as_str())
        total += 1
    batch = receiver.receive(timeout=5000)

end_time = time.time()
client.stop()
run_time = end_time - start_time
print("Received {} messages in {} seconds".format(total, run_time))
except KeyboardInterrupt:
pass
finally:
client.stop()
```

it connects , but never actully views the data
my sender is the same as that of the quickstart from azure tutorial

please help

**Comment by annatisch** [comment]
Hi @theamrzaki - thanks for the report!
The issue in this case might be the partition ID.

Notice that the quickstart guide is specifically sending messages to Partition "0", whereas the code you've posted above is receiving messages from Partition "1".
These will both need to point to the same partition.

Alternatively, you can remove the partition ID from the sender entirely - this will then allocate messages to all partitions via round robin. You would then need to add a receiver for each partition in order to receive all messags.

I hope this helps! Let me know how it goes :)

**Comment by annatisch** [comment]
Hi @theamrzaki - were you able to get this working?

**Comment by theamrzaki** [comment]
I am working on a simple scenario , where the sender always sends data , and the receiver can open at any time (not always running ) and it would receive realtime data.

I think EventProcessorHost  would be the most suitable because of having checkpoints , what do you think ?

I was thinking that after each sending of data , a checkpoint would be created , so that at any time the receiver connects , it would read real-time data

**Comment by annatisch** [comment]
Thanks @theamrzaki - indeed you can use checkpointing with EventProcessorHost, however EPH isn't a requirement if you only want the receiver to receive the "latest" messages.

You can add an offset to the receiver, this could be the sequence number of the last received message, or it could be a timestamp (i.e. only receive messages from this time forward), or you can simply use the keyword `@latest` which will only receive new messages that come through after the receiver has attached. 

You can see the documentation for the Offset object here:
https://docs.microsoft.com/en-us/python/api/azure-eventhub/azure.eventhub.common.offset?view=azure-python

Additionally you can see examples of how I've used them in my tests here:
- [Using `@latest` offset](https://github.com/Azure/azure-event-hubs-python/blob/master/tests/test_receive.py#L15)
- [Using datetime offset](https://github.com/Azure/azure-event-hubs-python/blob/master/tests/test_receive.py#L95)
- [Using sequence number offset](https://github.com/Azure/azure-event-hubs-python/blob/master/tests/test_receive.py#L127)

Using the sequence number offset is what EPH is doing.

**Comment by annatisch** [comment]
Hi @theamrzaki - let me know if using the Offset feature help with your scenario :)

**Comment by theamrzaki** [comment]
Thanks @annatisch  for your reply ,

I have tried many complicated scenarios to just view real time data ( i was receiving a batch and then i would compare the date-time) , but your offset ="@latest" works just fine .

I just wanted to ask you ,do custom endpoints override built-in endpoints data , 
i mean , if i have a built-in endpoint that sends all telemetry data , i discovered that when creating a rule (tempalert) , data with property (tempalert) are not seen in built-in endpoint , is this the case ?

I have managed to view all route data through creating a route with rule (true) , to route all telemetry data , but now i am not using built-in endpoints at all , it this the most optimized method to view all telemetry data ?
