### ISSUE TITLE
Writing to EventHub Capture, when reading from PySpark, body is not being decoded

### ISSUE THREAD

**Issue by roalexan** [Azure/azure-event-hubs-python#83]
I have a DataBricks notebook where I send a message to EventHub with a Capture writing to Azure Storage. When I try to read this file into a Spark dataframe, the "body" field is binary (not properly decoded). I would expect that this "body" field should be properly decoded.

Here's how I send a message to EventHub:

    from azure.eventhub import EventHubClient, Sender, EventData
    import time

    authorization_rules = list(eventHubManagementClient.namespaces.list_authorization_rules(RESOURCE_GROUP_NAME, NAMESPACE_NAME))
    default_authorization_rule_name = authorization_rules[0].name

    accessKeys = eventHubManagementClient.namespaces.list_keys(RESOURCE_GROUP_NAME, NAMESPACE_NAME, default_authorization_rule_name)

    ADDRESS = "amqps://{0}.servicebus.windows.net/{1}".format(NAMESPACE_NAME, EVENT_HUB_NAME)
    USER = accessKeys.key_name
    KEY = accessKeys.primary_key

    client = EventHubClient(ADDRESS, debug=False, username=USER, password=KEY)
    sender = client.add_sender(partition="0")
    client.run()
    try:
        start_time = time.time()
        for i in range(5):
            print("Sending message: {}".format(i))
            message="test message"
            sender.send(EventData(message))
    except:
        raise
    finally:
        end_time = time.time()
        client.stop()
        run_time = end_time - start_time
        print("Runtime: {} seconds".format(run_time))

Here's how I read it into a Spark dataframe (for example):

    df = spark.read.format("com.databricks.spark.avro").load("dbfs:/mnt/container2/rbaeventhubnamespace/rbaeventhub/0/2018/11/29/16/01/30.avro")
    display(df)

    SequenceNumber | Offset | EnqueuedTimeUtc | SystemProperties | Properties | Body
    10 | 792 | 11/29/2018 4:01:42 PM | {} | {} | MTE3LDU1LDE=

Note that the "Body" field is encoded. This is the crux of the problem - why is it not coming back decoded?

Is it a problem, perhaps, that when looking at the raw avro file I see the field definition as:

"fields":[{"name":"SequenceNumber","type":"long"},{"name":"Offset","type":"string"},
{"name":"EnqueuedTimeUtc","type":"string"},{"name":"SystemProperties","type":{"type":"map","values":["long","double","string","bytes"]}},
{"name":"Properties","type":{"type":"map","values":["long","double","string","bytes","null"]}},{"name":"Body","type":["null","bytes"]}]}

It seems suspicious that the "Body" is of type "null".

**Comment by annatisch** [comment]
Thanks @roalexan!
I am not familiar with how data is loaded into the Spark dataframe - perhaps it is expecting message data to be formated/encoded in a particular way that therefore is giving us garbage data when it tries to load it?

Additionally - are you sure that the message being loaded here is in fact the same message that you are sending with a body of "test message"? Messages will persist in an EventHub for some time (~a week) so unless you have configured the receiver to **_only_** collect the latest messages (or messages after a certain offset) then perhaps the message we are seeing here had different body data?

**Comment by roalexan** [comment]
For part 2, I am sure. Because I'm paranoid, I have some helper python scripts that I run locally to 1) delete all the blobs from my container, 2) get all the blobs from the container, 3) print all the (avro) blobs from the container. Between tests, I delete everything, add my message to EventHub, then get the one and only (avro) blob written (after 1 minute).

For what it is worth, [here ](https://docs.azuredatabricks.net/_static/misc/episodes.avro) is a sample avro data file that I can read correctly into a Spark dataframe. I've also attached it to this writeup. Attached is also one of my avro files that is not being decoded properly. You'll see they are close, but I'm suspicious of the field definition, in particular the "Body".

[working.txt](https://github.com/Azure/azure-event-hubs-python/files/2630712/working.txt)
[notworking.txt](https://github.com/Azure/azure-event-hubs-python/files/2630713/notworking.txt)

**Comment by roalexan** [comment]
BTW, I should add that I CAN print out the unencoded content from my Python command line if I use files. So, perhaps a workaround is to get the files in the Python notebook, and take a similar approach. However, this doesn't seem ideal.

For example:

    import avro.schema
    from avro.datafile import DataFileReader, DataFileWriter
    from avro.io import DatumReader, DatumWriter

    try:
        reader = DataFileReader(open("episodes.avro", "rb"), DatumReader())
        for user in reader:
            print(user)
        reader.close()
    except Exception as e:
        print(e)
    finally:
        input("Press Enter to exit...")

**Comment by roalexan** [comment]
Yes, quite unknown to me how the encoding for the working case got in there, nor how the extra stuff for the non-working case got in there. FWIW, there is a link [here ](https://stackoverflow.com/questions/53197825/pyspark-deserializing-an-avro-serialized-message-contained-in-an-eventhub-captu
)that does a better job at capturing the essense of this bug.

**Comment by annatisch** [comment]
Thanks for the link @roalexan - what owns the process of reading an event from EventHub (e.g. "test message) and converting it into this formatted file? (Which, if I am understanding correctly, is then failing to be properly read by pySpark)

**Comment by roalexan** [comment]
Turns out this was a misunderstanding on my part. The "body" bytes in the message are fine, it's just that they have to be cast to a string or JSON, depending on your needs. 

For example:
```
jsonRdd = df.select(df.Body.cast("string"))
display(jsonRdd)
data = spark.read.json(jsonRdd)
display(data)
```

I'm going to close this issue.

**Comment by annatisch** [comment]
Great to hear that it's resolved! Thanks for following up @roalexan and posting your solution :)
