### ISSUE TITLE
Error in running example

### ISSUE THREAD

**Issue by james-tn** [Azure/azure-event-hubs-python#86]
Try to run the example with producer after running the setup script.
I have error as below:
%3|1545079866.100|ERROR|python-example-producer#producer-1| [thrd:sasl_ssl://evenhubkafka.servicebus.windows.net:9093/bootstrap]: sasl_ssl://xxxx.servicebus.windows.net:9093/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 7ms in state CONNECT)
How to fix this?

Thanks

James

**Comment by annatisch** [comment]
Thanks @james-tn. I have not seen this error before - which producer sample are you running?

**Comment by james-tn** [comment]
It’s here https://github.com/Azure/azure-event-hubs/tree/master/samples/kafka/python
In this producer: https://github.com/Azure/azure-event-hubs/blob/master/samples/kafka/python/producer.py

Thanks

James

**Comment by annatisch** [comment]
Thanks for the details @james-tn - the Producer sample there does not appear to be using the EventHubs Python SDK.
I was about to recommend opening an issue in that repo - however it does not look like they have enabled issues....

Adding @basilhariri and @JamesBirdsall here so that they can enable issues on their repo for supporting the samples.

**Comment by basilhariri** [comment]
Hi all, that sample is deprecated. Please use the new repo's [sample](https://github.com/Azure/azure-event-hubs-for-kafka/tree/master/quickstart/python) instead. The kafka samples on this repo will be deleted soon, so please update any link you have to reference the new repository at https://github.com/Azure/azure-event-hubs-for-kafka/

Thanks.

**Comment by james-tn** [comment]
Same error when I use the new repo.
I setup fresh with a new ubuntu DSVM on Azure.

**Comment by basilhariri** [comment]
Hi James, could you open an issue on the EventHubs for Kafka repo? It’ll help us keep track of this issue and also let others who run into a similar problem see the thread as well

**Comment by james-tn** [comment]
Yes it's here: https://github.com/Azure/azure-event-hubs-for-kafka/issues/28
