### ISSUE TITLE
GZipped message is not received correctly in batch mode

### ISSUE THREAD

**Issue by jelther** [Azure/azure-event-hubs-python#94]
I'm trying to send a message batch of gzipped strings to an Event Hub using the example library.
However, If I use the following constructor of the EventData class

> eventData = EventData(batch=message)
> sender.send(eventData)

(where "message" is a list of compressed string bytes.)

the message is not received on the EventHub.

Believe it or not, If I send the same list using the following loop, the message arrives correctly:

>for i in message:
>	sender.send(EventData(i))

Is there any limitation regarding to bytes or a list of bytes ?

Thanks!

**Comment by annatisch** [comment]
Hi @jelther - thanks for the report!
Sorry for the delay - I have been away.

This is certainly interesting.
What is the potential size of the batch of data in `message`?
What OS are you currently using? We've got an open issue with regards to sending messages over a certain size particularly on OSX (and certain linux distros) as reported in issue #76.

Are you able to give me a sample data set for the `message` value that I could use to test locally?

Thanks!

**Comment by jelther** [comment]
HI @annatisch .
The message size is random, I've tried several sizes (under the 256kb limit, of course) and the OS I'm using is Centos 7, with Python 3.7.

I can't put the real message here due to industrial secrets but I can generate a sample.

I'll try to attach it here in the next days.

**Comment by jelther** [comment]
@annatisch , you can find a sample core here in this Gist : https://gist.github.com/jelther/dc2875a08fdbaab9e233b896cb0a1bcd

I've tried to reproduce the "byte character error" with some random data but I couldn't.

Despite of that, using different methods to send the data (as described in the comments) generate different errors. For example , if I send through the "batch=" parameter, the EventHubClient rises the message limit size. Iterating before sending doesn't.

It's very curious!

In my production environment I'm iterating before sending.

**Comment by annatisch** [comment]
Hi @jelther 
Yes this is the behavior I would expect.
When you use the `batch=` parameter, we attempt to pack multiple messages into a single payload. This reduces message overhead and can greatly increase message throughput performance. However, this can therefore hit the max size of an individual message and raise and error.

Instead, when you iterate over the data and call send on each individual segment, it will be creating and sending a separate message for each piece.

You mention that the data size would be under 256kb - would it likely also be under 128kb? (This was the size that messages on OSX started having trouble.)

**Comment by jelther** [comment]
@annatisch , got it.

And about the message being under 128kb : sometimes it's under this size. The size varies because I'm loading different data and I'm only limiting to the maximum size that the EventHub allows.

**Comment by annatisch** [comment]
Gotcha - well it seems that if you're getting any kind of "message too large" error at all it will not be the same issue as #76 - as in this case the send process was just hanging.

So is the main issue the byte character error you're seeing with your data?

**Comment by jelther** [comment]
@annatisch , yes. Since it's expected to iterate before sending, the issue regarding the size it's ok.

Now, the problem I've had when I was sending bytes I couldn't reproduce again.
I'll try to dig deeper and see if it happens again but the code I'm using is in that gist above.

**Comment by annatisch** [comment]
Thanks @jelther - in that case I will close this particular issue as it deals mostly with the question around message size.
If you are able to reproduce the encoding error, please open a fresh error with the specific logs/stacktrace. :)
