### ISSUE TITLE
Receiving single characters instead of whole message

### ISSUE THREAD

**Issue by jacobpledger** [Azure/azure-event-hubs-python#95]
Hi, I'm having trouble with receiving messages. I'm able to push a list of jsonified python objects (serialized django model objects) into an event hub, but when receiving them, they seem to come in character-by-character. My receiver is almost identical to the one in your examples (and I can't see any obvious place where I'm doing something dumb like iterating over a string).
I'm wondering if you can maybe help point me to what I'm doing wrong.

**Comment by jacobpledger** [comment]
Never mind, I knew I'd find what I'd done as soon as I publicly asked a question.

**Comment by annatisch** [comment]
Thanks @jacobpledger - sorry for the delayed response - I have been on vacation.
Great to hear that you managed to resolve the issue! :)

Just in case anyone else encounters this behaviour - could you let us know what your solution was? :)

**Comment by jacobpledger** [comment]
Sure, I was serializing the objects through a Django REST Framework ModelSerializer with `many=True`. So it took a list of objects and turned them all to JSON, but specifically a JSON _string_. Printing it looked like a list of dicts, but because it was actually a string, when I went to push the elements one at a time, each element was a single character.
Ex. / dramatic reenactment:
Wrong way:
```
data = models.Foo.all()
serialized_data = serializers.FooSerializer(data, many=True)
json_data = JSONRenderer().render(serialized_data)  # json_data is actually a string!
event_hub = AzureEventHub()
event_hub.batch_send(messages=json_data)
```
Right way:
```
data = models.Foo.all()
azure_data = []
for item in data:
    serialized_data = serializers.FooSerializer(data)
    json_data = JSONRenderer().render(serialized_data)
    azure_data.append(json_data)
event_hub = AzureEventHub()
event_hub.batch_send(messages=azure_data)
```

**Comment by annatisch** [comment]
Thanks for the details @jacobpledger - much appreciated :)
