### ISSUE TITLE
Can't use receiver.receive method to receive specified number data with prefetch and max_batch_size flag

### ISSUE THREAD

**Issue by yuhaii** [Azure/azure-event-hubs-python#98]
I am testing customer’s Event hub python client code.

I have 3963 messages in the event hub. I set the prefetch=8000, max_batch_size=5000. It should prefetch 8000 events and receive 5000 events at one time.

![image](https://user-images.githubusercontent.com/39817657/53221910-85df8480-36a6-11e9-9be1-3d19ed89c5dc.png)

But it received about only 100 message at one time. I am not sure how many messages it prefetched. And I notice it didn’t receive all message in event hub.

![image](https://user-images.githubusercontent.com/39817657/53221950-ae677e80-36a6-11e9-91d2-d47ae6f73b21.png)

I didn’t see there is any perfetch or max_batch_size limitation limitation in our SDK document:

![image](https://user-images.githubusercontent.com/39817657/53221960-ba534080-36a6-11e9-820e-98d47deecbdd.png)

![image](https://user-images.githubusercontent.com/39817657/53221974-c2ab7b80-36a6-11e9-8fd2-01c02c50166b.png)

Did I miss something in the code? Do you have any suggestions? Thanks in advance!

**Comment by yuhaii** [comment]
I try to find the clue in EH python SDK source code, but I do not see the "receive_message_batch" function definition. Please help us!

![image](https://user-images.githubusercontent.com/39817657/53228264-a239ec00-36bb-11e9-8174-6a17dd278a2f.png)

**Comment by yuhaii** [comment]
I list the source code below.  azure-eventhub Version: 1.3.0

#!/usr/bin/env python

import os
import sys
import time
import logging
import asyncio
from azure.eventhub import Offset, EventHubClient, Receiver

	client = EventHubClient(ADDRESS, debug=False, username=USER, password=KEY)
	receiver = client.add_receiver(CONSUMER_GROUP,"0",prefetch=8000,offset=OFFSET,keep_alive=60)
	client.run()
	
	batch = receiver.receive(timeout=60, max_batch_size=5000)
	cnt = len(batch)
	print("cnt len : " + str(cnt))
	while batch:
		#for events in batch:
		#	print("events :" + str(events))
		cnt = cnt + len(batch)
		batch = receiver.receive(timeout=60)
		print("After the loop, cnt len : " + str(cnt)) 

![image](https://user-images.githubusercontent.com/39817657/53228483-52a7f000-36bc-11e9-8c4e-8672e5eb697a.png)

**Comment by yuhaii** [comment]
@annatisch , good day. do you have any suggestions? thanks in advance!

**Comment by annatisch** [comment]
Hi @yuhaii - thanks for the report!
The value set for `prefetch` and `max_batch_size` are not guarantees - and the actual number of events returned will vary and depend on the speed of the connection.

However it should still receive all of the events in the EventHub - are you not receiving all 3963 events?

**Comment by yuhaii** [comment]
@annatisch , thanks for your reply!

I made the test again. I use our "service bud explorer tool" and send 3963 messages to event hub:
![image](https://user-images.githubusercontent.com/39817657/53294420-48533680-3821-11e9-9fed-d47d174adcac.png)

Then I use same code to receive the message. We can see it just hang there after received 2040 messages.
![image](https://user-images.githubusercontent.com/39817657/53294432-9d8f4800-3821-11e9-988d-815210a94815.png)

I attached the source file for reference:

[EventHubTestPrefech2.zip](https://github.com/Azure/azure-event-hubs-python/files/2897522/EventHubTestPrefech2.zip)

Thank you!
Hai

**Comment by annatisch** [comment]
Thanks for the info @yuhaii - I see you are only receiving from partition "0". Is it possible the remaining events are in a different partition?

**Comment by yuhaii** [comment]
Thank you! @annatisch . Understand. I have removed that event hub.

**Comment by annatisch** [comment]
Great @yuhaii - does this mean receiving from multiple partitions has resolved the issue?

**Comment by annatisch** [comment]
Hi @yuhaii - please let me know if this is still unresolved :)

**Comment by yuhaii** [comment]
This issue solved. Thanks for your help! @annatisch
